version: '3'
services:
  backend:
    image: express-app
    build: ./backend
    command: node src/app.js
    ports:
      - "8081:8081"
    volumes: 
      - ./:/backend
      - ./backend/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    