version: '3'
services:
  frontend:
    image: vue-app
    build: ./frontend
    command: npm run dev
    ports:
      - "8080:8080"
    depends_on:
      - "backend"
  backend:
    image: express-app
    build: ./backend
    command: node src/app.js
    ports:
      - "8081:8081"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    