version: '3'
services:
  backend:
    image: express-app
    build: .
    command: node src/app.js
    ports:
      - "8081:8081"
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    